In [1]:
import numpy as np

In [2]:
z = np.zeros((5,4))
print(z)
print("Dimension:", z.ndim, "Shape:", z.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Dimension: 2 Shape: (5, 4)


In [3]:
matrix = []
for i in range(5):
    row = []
    for j in range(4):
        row.append(i-j)
    matrix.append(row)
    print(row)

[0, -1, -2, -3]
[1, 0, -1, -2]
[2, 1, 0, -1]
[3, 2, 1, 0]
[4, 3, 2, 1]


In [ ]:
# the same seed, produce the same sequence of number
rng_matrix = np.random.randint(1,10,size=(5,6))
print(rng_matrix)

[[8 2 1 3 3 7]
 [1 6 3 2 2 9]
 [9 5 6 4 7 5]
 [8 7 7 1 4 7]
 [1 6 8 6 8 8]]


In [21]:
x = np.zeros(10)
print(x)
y = x.reshape((5,2))
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
matrix = np.ones((3,5))
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# how to save 2 matrices in a file?
# always use binary format, not text format!!!

'''
Text format
    np.savetxt

Binary Format
    np.save --> .npy standard format
    np.savez --> .npz uncompressed format (for many arrays)
    np.savez_compressed --> compressed version of savez
    np.load --> loading .npy or .npz
'''

X = np.random.randint(1, 100, size=(5,5))
Y = np.random.randint(1, 100, size=(5,5))

np.savez('data.npz', X=X, Y=Y) # saves in binary format
data = np.load('data.npz')

np.savetxt('readable.txt', X, fmt="%d") # saves in human text

print(data['X'])
print(data['Y'])

[[74 57 25 22 70]
 [28 82 87 15 68]
 [87 61 97 44 84]
 [10 81  6 81 14]
 [84 37 30 50 87]]
[[49 10 80 43 53]
 [55 24 74 48 37]
 [13 85 74 65 70]
 [73 14 91 65 20]
 [ 6 38 61 37 62]]
